import LazyLoad from "vanilla-lazyload";
import Swiper from "swiper";
import { Navigation, Pagination } from "swiper/modules";
import { isBrowserSupportWebp } from "./modules/support-webp.js";

import { animCircleText } from "./modules/animate-circle.js";
import { validInputs } from "./modules/valid-inputs.js";
import { formHandle } from "./modules/form-handle.js";
import { validateForm } from "./modules/validate.js";
import { handleMobileMenu } from "./modules/mobile-menu.js";
import { accordeonFunc } from "./modules/accordeon.js";
import { blogHandledFunc } from "./modules/blog-handled.js";
import { swiper } from "./modules/swiper.js";
import { registerForm } from "./modules/register-form.js";
import { map } from "./modules/map.js";
import { modal } from "./modules/modal.js";
import { statusForm } from "./modules/status-form.js";
import { contractForm } from "./modules/contract-form.js";
import { selector } from "./modules/selector.js";
import { tabs } from "./modules/tabs.js";
import { representativeTab } from "./modules/representative-tab.js";
import { wheel } from "./modules/wheel.js";
import { tabeFix } from "./modules/table-fix.js";
import { tableTab } from "./modules/table-tab.js";
import { inputs } from "./modules/inputs.js";
import { fancy } from "./modules/fancy.js";
import { header } from "./modules/header.js";
import { tooltips } from "./modules/tooltips.js";
import { forms } from "./modules/forms.js";
import { datePicker } from "./modules/date-picker.js";

fancy();
inputs();
tableTab();
tabeFix();
tabs();
representativeTab();
wheel();
header();
tooltips();
forms();
modal();
selector();
statusForm();
contractForm();
isBrowserSupportWebp();
swiper();
animCircleText();
formHandle();
handleMobileMenu();
accordeonFunc();
blogHandledFunc();
map();
registerForm();
datePicker();

// validInputs();
// validateForm();
//handleAttachFiles();

let myLazyLoad = new LazyLoad();
myLazyLoad.update();
